<a href="https://colab.research.google.com/github/ljflinux/LLM/blob/main/%E4%BB%8E%E9%9B%B6%E6%9E%84%E5%BB%BA%E5%A4%A7%E6%A8%A1%E5%9E%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#《从零构建大模型》

图书地址：https://weread.qq.com/web/bookdetail/52e320c0813ab9edeg01750f

代码地址：https://github.com/rasbt/LLMs-from-scratch/tree/main

## 第一章 理解大模型语言

### 1.1 什么是大语言模型

### 1.2 大语言模型的应用

### 1.3 构建和使用大语言模型的各个阶段

### 1.4 Transformer 架构介绍

### 1.5 利用大型数据集

### 1.6 深入刨析GPT架构

### 1.7 构建大语言模型

### 1.8 小结

## 第二章 处理文本数据

## 第三章 编码注意力机制

## 第四章 从头实现GPT模型进行文本生成

## 第五章 在无标签数据上进行预训练

## 第六章 针对分类的微调

## 第七章 通过微调遵循人类指令

## 附录A PyTorch简介

In [ ]:
import torch

tensor1d = torch.tensor([1, 2, 3])
print(tensor1d.dtype)

tensor2d = torch.tensor([[1, 2, 3],
             [4, 5, 6]])
print(tensor2d)

print(tensor2d.T)

print(tensor2d @ tensor2d.T)

torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[14, 32],
        [32, 77]])


In [ ]:
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

z = x1 * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

print(grad_L_w1)
print(grad_L_b)

loss.backward()
print(w1.grad)
print(b.grad)

(tensor([-0.0898]),)
(tensor([-0.0817]),)
tensor([-0.0898])
tensor([-0.0817])


In [ ]:
print(torch.cuda.is_available())

False


## 附录B 参考文献和延申阅读

## 附录C 练习的解决方案

## 附录D 为训练循环添加更多细节和优化功能

## 附录E 使用LoRA进行参数高效微调

## 附录F 理解推理大语言模型：构建与优化推理模型的方法与策略

## 看完了